spring:
  application:
    name : practice

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER
    username: host
    password: 1234
    driver-class-name: org.h2.Driver

